### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by Nin3s**
- renamed complanion to we-tinerary
- google/facebook login working
- added the mountains back to the 'about' page
- ye

### CODE REVIEW

**Comment by Victoria-Williamson** [comment]
Slight issue with the colors of the mountains and the textboxes, but we can fix this in the next PR

image

**Comment by Victoria-Williamson** [comment]
also one more question

should we maybe either make the google / facebook buttons line up vertically instead of horizontal. or use circle  picture buttons similar to the mobile app cause it looks like the text is wrapping
image

**Review by Victoria-Williamson — CHANGES_REQUESTED** [review]
Besides maybe fixing the button in the Third Party Auth component, everything looks really good!!

**Comment by Nin3s** [comment]
> also one more question
> 
> should we maybe either make the google / facebook buttons line up vertically instead of horizontal. or use circle picture buttons similar to the mobile app cause it looks like the text is wrapping image

I'll make a screenshot with both options and will let y'all decide!

**Comment by Nin3s** [comment]
- fixed the problems with the mountain svg by simply removing them from existence :clown: maybe they will come back another day
- added spinners/loaders in login and register forms for ui (when the user clicks on sign in/register, the buttons will be disabled and the spinner/loaders will appear)
- oauth buttons are now c i r c u l a r

**Review by Victoria-Williamson — APPROVED** [review]

**Comment by Victoria-Williamson** [comment]
LGTM

**Pull request merged**
